### ISSUE TITLE
default param value of " " is trimmed to an empty string ""

### ISSUE THREAD

**Issue by jdalton** [eslint/doctrine#157]
In the [doctrine demo](http://eslint.org/doctrine/demo/) try:
```
     * @param {string} [chars='     '] Foo.
```
Then in the dev console of the demo:
```js
var result = doctrine.parse($('#code').val(), { sloppy: true, unwrap: true });
```
You'll see the `result.tags[0]['default']` is `"''"` instead of `"'   '"`.

**Comment by nzakas** [comment]
Confirmed as a bug. Do you want to submit a PR?

**Comment by jdalton** [comment]
I looked through the code a bit but not too familiar with it or what to poke/patch.

**Comment by jdalton** [comment]
For now I'm fixing it in a postprocess I run on the output.

**Comment by nzakas** [comment]
I'm also still learning the code, as well. My hunch is that this has something to do with it:
https://github.com/eslint/doctrine/blob/master/lib/typed.js#L368

Either that or `scanString()` itself.

**Comment by kaicataldo** [comment]
Spent a little time on this and found the culprit: https://github.com/eslint/doctrine/blob/master/lib/doctrine.js#L359

The reason this is here is to skip whitespace between the brackets value - the problem is that it's also running inside strings. I believe the fix is to not run `skipWhiteSpace` if it's between two quotes, but I have no idea how to do that. I'll keep digging and will try to get a PR made ASAP.

**Comment by kaicataldo** [comment]
PR created
