### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/doctrine#226]
As discussed [here](https://eslint.org/blog/2018/11/jsdoc-end-of-life), this package is being deprecated and will no longer be maintained. As such, I think it would be a good idea to [archive](https://help.github.com/articles/archiving-repositories/) it. Are there any final changes we want to make before that happens?

**Comment by Aladdin-ADD** [comment]
agreed! and we might want to deprecated the package via `npm deprecate`. https://docs.npmjs.com/cli/deprecate

**Comment by not-an-aardvark** [comment]
Using `npm deprecate` will cause a warning to be displayed to ESLint users. Since we're not going to be removing `valid-jsdoc` and `require-jsdoc` for the forseeable future due to our [deprecation policy](https://eslint.org/docs/user-guide/rule-deprecation), that seems like it could be annoying since we're presumably not going to be switching to a different JSDoc parser just to support those rules.

**Comment by kaicataldo** [comment]
I've closed all existing PRs and issues. Additionally, I made a [quick PR](https://github.com/eslint/doctrine/pull/227) to update the readme so that those coming across the repository can quickly find context around why this project is no longer maintained. I'd like to land that before we archive the repo. Once that lands, I think we're good to go!

**Comment by not-an-aardvark** [comment]
That PR has landed, so I'm going to archive this repo.
